### ISSUE TITLE
Missing File: "config/alg/standard_loadvel.json" and "env/bin/activate"

### ISSUE THREAD

**Issue by R-Ceph** [eric-mitchell/macaw#1]
When running `bash ./scripts/macaw_vel.sh`
Error comes out that : 

> FileNotFoundError: [Errno 2] No such file or directory: 'config/alg/standard_loadvel.json'

> ./scripts/macaw_vel.sh: line 3: env/bin/activate: No such file or directory 

Would you like to provide  "config/alg/standard_loadvel.json"?
And dose "env/bin/activate" matters?

**Comment by eric-mitchell** [comment]
Hi Han! Sorry for the delay getting back to you. The `FileNotFoundError` is due to a mistake made when renaming/copying scripts to the current scripts directory layout. I've pushed a fix to main.

The `env/bin/activate` line assumes you've installed the requirements for the project to a virtualenv named `env` located at the top level of the project. If you have a different name/are using a different dependency manager, feel free to modify/remove this line.

I'll close this issue for now, but please feel free to re-open if you continue to have any issues!
